/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5Hi1ox3kim4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { getCarouselImages, getImgLink } from "@/lib/data";
import { useEffect, useState } from "react";
import ucekImage from "@/public/img/ucek.jpeg";
import Image from "next/image";

export function HeroSlider() {

  const [images, setImages] = useState<string[][]>([]);

  useEffect(() => {
    getCarouselImages().then((data) => {
      setImages(data);
    });
  }, []);

  return (
    <div className="relative w-full overflow-hidden">
      <Carousel className="w-full">
        <CarouselPrevious className="z-50"/>
        <CarouselNext className="z-50"/>
        <CarouselContent>
          <CarouselItem>
            <Image
              src={ucekImage}
              width={1920}
              height={1080}
              alt="Slider Image 1"
              className="h-[600px] w-full object-cover"
            />
          </CarouselItem>
          {images.map((image, index) => (
            <CarouselItem key={index}>
              <Image
                src={getImgLink(image[0])}
                width={1920}
                height={1080}
                alt={image[1]}
                className="h-[600px] w-full object-cover"
              />
            </CarouselItem>
          ))}
        </CarouselContent>
      </Carousel>
      <div className="absolute inset-0 flex flex-col items-center justify-center space-y-4 px-4 text-center text-white">
        <h1 className="text-4xl font-bold text-primary-foreground sm:text-5xl md:text-6xl">
         University College of Engineering
        </h1>
        <p className="max-w-[600px] text-lg text-primary-foreground">
          Kariavattom
        </p>
      </div>
    </div>
  )
}
